# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.gast-network.com:
    container_name: orderer.gast-network.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/gast-network.com/orderers/orderer.gast-network.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/gast-network.com/orderers/orderer.gast-network.com/tls/:/var/hyperledger/orderer/tls
        - orderer.gast-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.gast1.gast-network.com:
    container_name: peer0.gast1.gast-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.gast1.gast-network.com
      - CORE_PEER_ADDRESS=peer0.gast1.gast-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.gast1.gast-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gast1.gast-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gast1.gast-network.com:7051
      - CORE_PEER_LOCALMSPID=Gast1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gast1.gast-network.com/peers/peer0.gast1.gast-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gast1.gast-network.com/peers/peer0.gast1.gast-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gast1.gast-network.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.gast1.gast-network.com:
    container_name: peer1.gast1.gast-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.gast1.gast-network.com
      - CORE_PEER_ADDRESS=peer1.gast1.gast-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.gast1.gast-network.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gast1.gast-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gast1.gast-network.com:7051
      - CORE_PEER_LOCALMSPID=Gast1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gast1.gast-network.com/peers/peer1.gast1.gast-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gast1.gast-network.com/peers/peer1.gast1.gast-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.gast1.gast-network.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.gast2.gast-network.com:
    container_name: peer0.gast2.gast-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.gast2.gast-network.com
      - CORE_PEER_ADDRESS=peer0.gast2.gast-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.gast2.gast-network.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gast2.gast-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gast2.gast-network.com:10051
      - CORE_PEER_LOCALMSPID=Gast2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gast2.gast-network.com/peers/peer0.gast2.gast-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gast2.gast-network.com/peers/peer0.gast2.gast-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gast2.gast-network.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.gast2.gast-network.com:
    container_name: peer1.gast2.gast-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.gast2.gast-network.com
      - CORE_PEER_ADDRESS=peer1.gast2.gast-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.gast2.gast-network.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gast2.gast-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gast2.gast-network.com:9051
      - CORE_PEER_LOCALMSPID=Gast2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gast2.gast-network.com/peers/peer1.gast2.gast-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gast2.gast-network.com/peers/peer1.gast2.gast-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.gast2.gast-network.com:/var/hyperledger/production
    ports:
      - 10051:10051
